### ISSUE TITLE
when claiming rewards, the UI popup should default to "All" validators

### ISSUE THREAD

**Issue by zramsay** [OmniFlix/insync#29]
current UX is defaulting to the first validator in the list. 99.9% of the time, the user will be claiming rewards from all validators and this feature request would speed things up.

**Comment by harish551** [comment]
@SrikanthSoparla consider this for next updates on insync

**Comment by SrikanthSoparla** [comment]
Okay.

**Comment by harish551** [comment]
> current UX is defaulting to the first validator in the list. 99.9% of the time, the user will be claiming rewards from all validators and this feature request would speed things up.

hey @zramsay this feature was now deployed
